# Generated by Django 5.2.11 on 2026-02-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_invoice_alter_ticket_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='document',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='invoice',
        ),
        migrations.AddField(
            model_name='ticket',
            name='document_bundle',
            field=models.FileField(blank=True, help_text='Archive with documents (.zip, .pdf)', null=True, upload_to='client_docs/', verbose_name='Client Documents'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price Paid'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='result_document',
            field=models.FileField(blank=True, null=True, upload_to='results/', verbose_name='Result Document'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='service_name',
            field=models.CharField(default='Unknown Service', max_length=255, verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='variant_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid / Waiting for Docs'), ('pending', 'Pending Review'), ('processing', 'Processing'), ('ready', 'Ready'), ('rejected', 'Rejected')], default='paid', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_note',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
