# Generated by Django 5.2.11 on 2026-02-10 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_ticket_document_remove_ticket_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='document_bundle',
            field=models.FileField(blank=True, null=True, upload_to='client_docs/', verbose_name='Legacy Bundle'),
        ),
        migrations.CreateModel(
            name='TicketFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_files/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tickets.ticket')),
            ],
        ),
    ]
