# Generated by Django 5.2.11 on 2026-02-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_assigned_to_ticketlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
